services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skillsrock-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - APP_PORT=3000
      - APP_NAME=TaskAppSkillsRock
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=taskdb
    restart: unless-stopped
    networks:
      - skillsrock-network

  postgres:
    image: postgres:latest
    container_name: skillsrock-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - skillsrock-network

networks:
  skillsrock-network:
    driver: bridge

volumes:
  postgres-data:
